# Generated by Django 4.2.23 on 2025-09-21 06:39

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
