# Generated by Django 4.2.23 on 2025-09-21 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_comment_datetime_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
